name: Manual Trigger with Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment (dev, staging, prod)"
        required: true
        default: "dev"
      version:
        description: "Enter version number"
        required: false

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Show Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
